### PR TITLE
Various - removing old stuff and updating to new hotness

### PR DESCRIPTION
**Pull request by atompkins**
@gschizas & @yuuzhan 

Fix Profile Inventory Select All
Move JQ_Wrapper after GM_ shim
Update buff list
Remove more Old UI code
Composing enhancements
Remove old AH functions. Restore auto fill min bid, cancel all and sort by current bid.
Fix Quick Extract. Only show resources. Make asynchronous call.
Fix trade screen, make asynchronous call.
Remove synchronous calls from inventory manager

### CODE REVIEW

**Comment by atompkins** [comment]
Don't merge this yet, there is a bug with UFSG.

**Comment by atompkins** [comment]
Should be OK now

**Comment by atompkins** [comment]
@fallenswordhelper/owners is anybody looking at this?
I don't really want to merge my own code but I need to move on and i'm on holiday in less than 2 weeks.

**Comment by yuuzhan** [comment]
Sorry, I am very new to GitHub lol - trying to figure out how!

**Comment by yuuzhan** [comment]
I think that did it.  I glaced at everything - looks good :)

**Pull request merged**
