### PR TITLE
Ajaxified questbook

### PR DESCRIPTION
**Pull request by ahanden**

### CODE REVIEW

**Comment by ahanden** [comment]
#427

**Comment by atompkins** [comment]
I would prefer this to be a dialog from the helper menu rather than blowing away the in-game stuff. The alternative would be to do progressive enhancement to what is there.
Any idea why the sorts are not working as expected?
When changing "status" it should update lastActiveQuestPage if storeLastQuestPage and associated prefs.
I'll fixup the API call and fallback.

**Comment by ahanden** [comment]
Tried using the ModalTitled module, but the close button doesn't work.

**Comment by atompkins** [comment]
the svelte questbook should be under notepad.
unknown page still needs to call questbookFull. unknown page is for POSTs where we don't have cmd & subcmd. it is possible that this is a legacy thing, not sure.
i'll figure out why close isn't working.

**Comment by atompkins** [comment]
needs telemetry on the buttons
should remember last selection used

**Comment by atompkins** [comment]
a loader is a dynamic import - import('../../../notepad/questbook/injectQuestBook')

the way you have it QuestBook.svelte is part of the core package so it loads on every page.

**Comment by atompkins** [comment]
ModalTitled needs an on:close={} handler

You have to track your own visibility because the dialogue could be re-opened without a page refresh.

**Pull request closed without merging**
