### PR TITLE
==Revision 1515 (PointyHair)==

### PR DESCRIPTION
**Pull request by atompkins**
\# (major) FS: Performance enhancements for lots of screens
  \# (major) FS: Performance enhancements for Environment (all page loads)
  \# (major) FS: Begin converting to new linter - ESLint
  \# (minor) FS: Clear Storage Button #58
  \# (minor) FS: Ajaxify Bank Deposits #101
  \# (minor) FS: Ajaxify Bank withdrawals and apply to guild bank
  \# (minor) FS: Fix rank scroll amount
  \# (minor) FS: New preferences: draggable Helper Menu, QuickLinks
  \# (minor) FS: New preference: Show Extra Links in Drop/Store
  \# (minor) FS: Fix rank scroll amount
  \# (minor) FS: Faster by default. Most options turned off
  \# (minor) FS: Updated buggy Cancel All button in AH

### CODE REVIEW

**Comment by atompkins** [comment]
@yuuzhan hiya :) enjoying the summer?

**Comment by yuuzhan** [comment]
@atompkins  Looks like you have an a screen filled summer!  Ill try to get to this soon.

**Comment by atompkins** [comment]
@yuuzhan yeah well the weather is cack here :(

**Comment by yuuzhan** [comment]
Looks Good.  I think its funny to read some of your comments "Evil" "Bad jQuery".  I also found it amusing that in one check in you added a bunch of image codes, and in a future one its removed and replaced :P

**Pull request merged**
