### PR TITLE
Teleport cooldown overlay

### PR DESCRIPTION
**Pull request by ahanden**

### CODE REVIEW

**Comment by atompkins** [comment]
did you break travis?
do you get a blank bar at the bottom of the action list?
image
not on first load, only after action, like moving.

**Comment by ahanden** [comment]
> did you break travis?
If I did, I swear it wasn't by design.

> do you get a blank bar at the bottom of the action list?
On firefox, it didn't happen. I'll do some testing on Chrome.

**Comment by atompkins** [comment]
make sure you pull my commits before you change anything, i fixed it already.

**Comment by ahanden** [comment]
I didn't get that extra bar on the action list in FF or chrome, even after additional actions.

I did notice that the countdown was slow, so I fixed that.

**Pull request merged**
