### PR TITLE
Settings

### PR DESCRIPTION
**Pull request by ahanden**
Rewrote the whole settings page in svelte.

### CODE REVIEW

**Comment by ahanden** [comment]
This pull throws *tons* of warnings: a11y-label-has-associated-control

**Comment by ahanden** [comment]
Got a bug I can't figure out - the combat evaluator bias setting keeps coming up empty.

**Comment by atompkins** [comment]
see what you think of this.
combat evaluator was having a problem with data types. option values are strings but bias is a number. you'll have to resave it to fix.
also you'll probably find you have a key called "GM_".

**Comment by ahanden** [comment]
Looks good to me.

**Pull request merged**
