### PR TITLE
faster-settings

### PR DESCRIPTION
**Pull request by atompkins**

### CODE REVIEW

**Review by ahanden — COMMENTED** [review]
Brilliant switch from svelte to html. I didn't even know we could import a file like that.

My only suggestion is to break the settings.html file into pieces like we did with the svelte apps for maintainability.

(Total aside: why is that module named `eventHandler5`?)

**Comment by atompkins** [comment]
We can do pretty much anything we like with plug-ins to the build system, just a matter of imagination.

Breaking up the file could present a challenge. That's why I put the regions in. In order for the minifier to work the html file has to be a valid fragment, I'm not sure how it would cope with orphan <tr>'s. I have a version that uses div's and grid layout, no perf difference that I can detect but might be easier to break up.

I'm getting more than 3X render improvement which is why I think it's worth talking about.

(eventhandler5 is just the 5th iteration of a common event handler. I was even worse at naming things then. Naming things is hard!)

**Comment by atompkins** [comment]
so this is a naive way of doing it. i realised afterwards that there is no need to perform the concatenation in real time, we can use a plug-in to do it at compile time. just gotta write the plug-in ;)

**Comment by atompkins** [comment]
i'm looking at [Pug](https://pugjs.org/api/getting-started.html) as an alternative

**Comment by atompkins** [comment]
@ahanden how about this?

**Pull request merged**
