### PR TITLE
new-group-join

### PR DESCRIPTION
**Pull request by atompkins**

### CODE REVIEW

**Comment by atompkins** [comment]
@ahanden what do you think of this?

**Comment by ahanden** [comment]
I've got a weird resizing issue while the spinner is present.

**Comment by atompkins** [comment]
how to repro?

**Comment by ahanden** [comment]
Whenever I clicked the join button, the icon would change to 50% width and the spinner would only be half on the screen. Removing the relative positioning fixed it for me on firefox.

**Comment by atompkins** [comment]
this is what happens on my systems without relative:
image

**Comment by ahanden** [comment]
Wild! The immediate difference I notice is our themes. I'm using classic and yours is grayscale.

**Comment by atompkins** [comment]
that's interesting. confirmed on classic theme. let me look into it.

**Comment by atompkins** [comment]
try that.
classic has some weird positioning that the other 2 don't!

**Comment by ahanden** [comment]
Works like a dream.

**Pull request merged**
